[package]
name = "websocket"
version = "0.1.0"
authors = ["Volker Mische <volker.mische@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
ws = "*"

[dependencies.js]
git = "https://github.com/servo/rust-mozjs.git"
